# Generated by Django 4.2.16 on 2025-11-12 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured_image_hash',
            field=models.CharField(blank=True, db_index=True, help_text='MD5 hash of image content for duplicate detection', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='featured_image_large',
            field=models.CharField(blank=True, help_text='Path to large size (1600x900)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='featured_image_medium',
            field=models.CharField(blank=True, help_text='Path to medium size (800x600)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='featured_image_thumb',
            field=models.CharField(blank=True, help_text='Path to thumbnail (300x200)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='postimage',
            name='image_file_hash',
            field=models.CharField(blank=True, db_index=True, help_text='MD5 hash of image content for duplicate detection', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='postimage',
            name='image_file_large',
            field=models.CharField(blank=True, help_text='Path to large size (1600x900)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='postimage',
            name='image_file_medium',
            field=models.CharField(blank=True, help_text='Path to medium size (800x600)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='postimage',
            name='image_file_thumb',
            field=models.CharField(blank=True, help_text='Path to thumbnail (300x200)', max_length=500, null=True),
        ),
    ]
