# Generated by Django 4.2.16 on 2025-11-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_featured_image_hash_post_featured_image_large_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=0, help_text='The order in which the category should be displayed.'),
        ),
        migrations.AddField(
            model_name='post',
            name='order',
            field=models.IntegerField(default=0, help_text='The order in which the post should be displayed.'),
        ),
    ]
