# Generated by Django 4.2.16 on 2025-12-13 09:59

from django.db import migrations, models
import posts.utils


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_category_order_post_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='featured_image_large',
        ),
        migrations.RemoveField(
            model_name='post',
            name='featured_image_medium',
        ),
        migrations.RemoveField(
            model_name='post',
            name='featured_image_thumb',
        ),
        migrations.RemoveField(
            model_name='postimage',
            name='image_file_large',
        ),
        migrations.RemoveField(
            model_name='postimage',
            name='image_file_medium',
        ),
        migrations.RemoveField(
            model_name='postimage',
            name='image_file_thumb',
        ),
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to=posts.utils.category_image_upload_to),
        ),
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to=posts.utils.post_image_upload_to),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image_file',
            field=models.ImageField(upload_to=posts.utils.post_gallery_image_upload_to),
        ),
    ]
