"""Profiles representing language and tradition specific localization assets."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, Iterable, List, Mapping

from .constants import (
    AMANTA_MONTH_NAMES,
    HORA_PLANETS,
    KARANA_NAMES,
    NAKSHATRA_NAMES,
    PAKSHA_NAMES,
    PURNIMANTA_MONTH_NAMES,
    SAKA_MONTH_NAMES,
    TITHI_NAMES,
    WEEKDAY_NAMES,
    YOGA_NAMES,
)


def _identity_map(values: Iterable[str]) -> Dict[str, str]:
    return {value: value for value in values}


def _extend_tithis(shukla_names: List[str], amavasya_name: str) -> List[str]:
    if len(shukla_names) != 15:
        raise ValueError("Need exactly 15 names for shukla paksha tithis")
    return shukla_names + shukla_names[:14] + [amavasya_name]


@dataclass(frozen=True)
class ProfileAssets:
    code: str
    language: str
    script: str
    section_titles: Mapping[str, str]
    field_labels: Mapping[str, str]
    event_labels: Mapping[str, str]
    tithi_full: List[str]
    nakshatra: List[str]
    paksha: List[str]
    karana: List[str]
    yoga: List[str]
    amanta_month: List[str]
    purnimanta_month: List[str]
    saka_month: List[str]
    weekday: List[str]
    hora_planet: List[str]
    auspicious_labels: Mapping[str, str] = field(default_factory=dict)
    inauspicious_labels: Mapping[str, str] = field(default_factory=dict)

    @property
    def hora_planet_map(self) -> Dict[str, str]:
        return {base: localized for base, localized in zip(HORA_PLANETS, self.hora_planet)}


# ---------------------------------------------------------------------------
# English profile (baseline)

ENGLISH_AUSPICIOUS_LABELS = {
    "Abhijit Muhurat": "Abhijit Muhurat",
    "Amrit Kaal": "Amrit Kaal",
    "Brahma Muhuratham": "Brahma Muhuratham",
    "Pratah Sandhya": "Pratah Sandhya",
    "Vijaya Muhurta": "Vijaya Muhurta",
    "Godhuli Muhurta": "Godhuli Muhurta",
    "Sayahna Sandhya": "Sayahna Sandhya",
    "Nishita Muhurta": "Nishita Muhurta",
}

ENGLISH_INAUSPICIOUS_LABELS = {
    "Rahu Kalam": "Rahu Kalam",
    "Yamagandam": "Yamagandam",
    "Gulika Kalam": "Gulika Kalam",
}

ENGLISH_PROFILE = ProfileAssets(
    code="en",
    language="English",
    script="Latin",
    section_titles={
        "date": "Date",
        "indian_civil": "Indian Civil Calendar",
        "lunar_context": "Lunar Context",
        "sun_moon": "Sun & Moon",
        "core_panchang": "Core Panchang",
        "traditional": "Traditional Panchang",
        "auspicious": "Auspicious Timings",
        "inauspicious": "Inauspicious Timings",
        "horas": "Horas",
        "festivals": "Festivals",
    },
    field_labels={
        "year": "Year",
        "month": "Month",
        "day_number": "Day",
        "amanta_month": "Amanta Month",
        "purnimanta_month": "Purnimanta Month",
        "paksha": "Paksha",
        "sunrise": "Sunrise",
        "sunset": "Sunset",
        "moonrise": "Moonrise",
        "moonset": "Moonset",
        "tithi": "Tithi",
        "nakshatra": "Nakshatra",
        "karana": "Karana",
        "yoga": "Yoga",
        "traditional_summary": "Summary",
        "day_horas": "Day Horas",
        "night_horas": "Night Horas",
        "no_festivals": "No festivals",
    },
    event_labels={
        "name": "Name",
        "start": "Start",
        "end": "End",
    },
    tithi_full=TITHI_NAMES,
    nakshatra=NAKSHATRA_NAMES,
    paksha=PAKSHA_NAMES,
    karana=KARANA_NAMES,
    yoga=YOGA_NAMES,
    amanta_month=AMANTA_MONTH_NAMES,
    purnimanta_month=PURNIMANTA_MONTH_NAMES,
    saka_month=SAKA_MONTH_NAMES,
    weekday=WEEKDAY_NAMES,
    hora_planet=HORA_PLANETS,
    auspicious_labels=ENGLISH_AUSPICIOUS_LABELS,
    inauspicious_labels=ENGLISH_INAUSPICIOUS_LABELS,
)


# ---------------------------------------------------------------------------
# Telugu profile

TELUGU_SHUKLA_TITHIS = [
    "పాడ్యమి",
    "విదియ",
    "తదియ",
    "చవితి",
    "పంచమి",
    "షష్ఠి",
    "సప్తమి",
    "అష్టమి",
    "నవమి",
    "దశమి",
    "ఏకాదశి",
    "ద్వాదశి",
    "త్రయోదశి",
    "చతుర్దశి",
    "పౌర్ణమి",
]

TELUGU_AUSPICIOUS_LABELS = {
    "Abhijit Muhurat": "అభిజిత్ ముహూర్తం",
    "Amrit Kaal": "అమృత కాలం",
    "Brahma Muhuratham": "బ్రహ్మ ముహూర్తం",
    "Pratah Sandhya": "ప్రాతః సాంధ్య",
    "Vijaya Muhurta": "విజయ ముహూర్తం",
    "Godhuli Muhurta": "గోదూలి ముహూర్తం",
    "Sayahna Sandhya": "సాయంసాంధ్య",
    "Nishita Muhurta": "నిశీత ముహూర్తం",
}

TELUGU_INAUSPICIOUS_LABELS = {
    "Rahu Kalam": "రాహు కాలం",
    "Yamagandam": "యమగండం",
    "Gulika Kalam": "గులిక కాలం",
}

TELUGU_PROFILE = ProfileAssets(
    code="te",
    language="Telugu",
    script="Telugu",
    section_titles={
        "date": "తేదీ",
        "indian_civil": "భారత జాతీయ క్యాలెండర్",
        "lunar_context": "చంద్ర మాస సమాచారం",
        "sun_moon": "సూర్య చంద్రోదయాలు",
        "core_panchang": "మూల పంచాంగం",
        "traditional": "సాంప్రదాయ పంచాంగం",
        "auspicious": "శుభ సమయాలు",
        "inauspicious": "అశుభ సమయాలు",
        "horas": "హోరాలు",
        "festivals": "పండుగలు",
    },
    field_labels={
        "year": "సంవత్సరం",
        "month": "మాసం",
        "day_number": "తేది",
        "amanta_month": "అమాంత మాసం",
        "purnimanta_month": "పౌర్ణిమాంత మాసం",
        "paksha": "పక్షం",
        "sunrise": "సూర్యోదయం",
        "sunset": "సూర్యాస్తమయం",
        "moonrise": "చంద్రోదయం",
        "moonset": "చంద్రాస్తమయం",
        "tithi": "తిథులు",
        "nakshatra": "నక్షత్రాలు",
        "karana": "కరణాలు",
        "yoga": "యోగాలు",
        "traditional_summary": "సారాంశం",
        "day_horas": "పగటి హోరాలు",
        "night_horas": "రాత్రి హోరాలు",
        "no_festivals": "ఈ రోజు ముఖ్యమైన పండుగలు లేవు",
    },
    event_labels={
        "name": "పేరు",
        "start": "ప్రారంభం",
        "end": "ముగింపు",
    },
    tithi_full=_extend_tithis(TELUGU_SHUKLA_TITHIS, "అమావాస్య"),
    nakshatra=[
        "అశ్విని",
        "భరణి",
        "కృతికా",
        "రోహిణి",
        "మృగశిర",
        "ఆర్ద్ర",
        "పునర్వసు",
        "పుష్యము",
        "ఆశ్లేష",
        "మఘ",
        "పూర్వ ఫాల్గుణి",
        "ఉత్తర ఫాల్గుణి",
        "హస్త",
        "చిత్ర",
        "స్వాతి",
        "విశాఖ",
        "అనురాధ",
        "జ్యేష్ఠ",
        "మూల",
        "పూర్వ ఆశాఢ",
        "ఉత్తర ఆశాఢ",
        "శ్రవణ",
        "ధనిష్ఠ",
        "శతభిషం",
        "పూర్వ భాద్రపద",
        "ఉత్తర భాద్రపద",
        "రేవతి",
    ],
    paksha=["శుక్ల పక్షం", "కృష్ణ పక్షం"],
    karana=[
        "బవ",
        "బాలవ",
        "కౌలవ",
        "తైతిల",
        "గరజ",
        "వణిజ",
        "విష్టి",
        "శకుని",
        "చతుష్పద",
        "నాగ",
        "కిమ్స్తుఘ్న",
    ],
    yoga=[
        "విష్కంభ",
        "ప్రీతి",
        "ఆయుష్మాన్",
        "సౌభాగ్య",
        "శోభన",
        "అతిగండ",
        "సుకర్మ",
        "ధృతి",
        "శూల",
        "గండ",
        "వృద్ధి",
        "ధ్రువ",
        "వ్యాఘాత",
        "హర్షణ",
        "వజ్ర",
        "సిద్ధి",
        "వ్యతిపాత",
        "వరియన్",
        "పరిఘ",
        "శివ",
        "సిద్ధ",
        "సాధ్య",
        "శుభ",
        "శుక్ల",
        "బ్రహ్మ",
        "ఇంద్ర",
        "వైదృతి",
    ],
    amanta_month=[
        "చైత్రం",
        "వైశాఖం",
        "జ్యేష్ఠం",
        "ఆషాఢం",
        "శ్రావణం",
        "భాద్రపదం",
        "ఆశ్వయుజం",
        "కార్తీకం",
        "మార్గశిరం",
        "పుష్య",
        "మాఘం",
        "ఫాల్గుణం",
    ],
    purnimanta_month=[
        "చైత్రం",
        "వైశాఖం",
        "జ్యేష్ఠం",
        "ఆషాఢం",
        "శ్రావణం",
        "భాద్రపదం",
        "ఆశ్వయుజం",
        "కార్తీకం",
        "మార్గశిరం",
        "పుష్య",
        "మాఘం",
        "ఫాల్గుణం",
    ],
    saka_month=[
        "చైత్ర",
        "వైశాఖ",
        "జ్యేష్ఠ",
        "ఆషాఢ",
        "శ్రావణ",
        "భాద్ర",
        "ఆశ్విన",
        "కార్తిక",
        "ఆగాహన",
        "పౌష",
        "మాఘ",
        "ఫాల్గున",
    ],
    weekday=[
        "సోమవారం",
        "మంగళవారం",
        "బుధవారం",
        "గురువారం",
        "శుక్రవారం",
        "శనివారం",
        "ఆదివారం",
    ],
    hora_planet=[
        "సూర్యుడు",
        "శుక్రుడు",
        "బుధుడు",
        "చంద్రుడు",
        "శని",
        "బృహస్పతి",
        "కుజుడు",
    ],
    auspicious_labels=TELUGU_AUSPICIOUS_LABELS,
    inauspicious_labels=TELUGU_INAUSPICIOUS_LABELS,
)


# ---------------------------------------------------------------------------
# Hindi profile

HINDI_SHUKLA_TITHIS = [
    "प्रतिपदा",
    "द्वितीया",
    "तृतीया",
    "चतुर्थी",
    "पंचमी",
    "षष्ठी",
    "सप्तमी",
    "अष्टमी",
    "नवमी",
    "दशमी",
    "एकादशी",
    "द्वादशी",
    "त्रयोदशी",
    "चतुर्दशी",
    "पूर्णिमा",
]

HINDI_AUSPICIOUS_LABELS = {
    "Abhijit Muhurat": "अभिजीत मुहूर्त",
    "Amrit Kaal": "अमृत काल",
    "Brahma Muhuratham": "ब्रह्म मुहूर्त",
    "Pratah Sandhya": "प्रातः संध्या",
    "Vijaya Muhurta": "विजय मुहूर्त",
    "Godhuli Muhurta": "गोधूलि मुहूर्त",
    "Sayahna Sandhya": "सायं संध्या",
    "Nishita Muhurta": "निशीथ मुहूर्त",
}

HINDI_INAUSPICIOUS_LABELS = {
    "Rahu Kalam": "राहु काल",
    "Yamagandam": "यमगण्ड",
    "Gulika Kalam": "गुलिक काल",
}

HINDI_PROFILE = ProfileAssets(
    code="hi",
    language="Hindi",
    script="Devanagari",
    section_titles={
        "date": "तारीख",
        "indian_civil": "भारतीय राष्ट्रीय पंचांग",
        "lunar_context": "चंद्र कैलेंडर विवरण",
        "sun_moon": "सूर्योदय/चंद्रोदय",
        "core_panchang": "मुख्य पंचांग",
        "auspicious": "शुभ मुहूर्त",
        "inauspicious": "अशुभ काल",
        "horas": "घंटाएँ",
        "festivals": "त्योहार",
    },
    field_labels={
        "year": "वर्ष",
        "month": "माह",
        "day_number": "दिन",
        "amanta_month": "अमान्त मास",
        "purnimanta_month": "पूर्णिमांत मास",
        "paksha": "पक्ष",
        "sunrise": "सूर्योदय",
        "sunset": "सूर्यास्त",
        "moonrise": "चंद्र उदय",
        "moonset": "चंद्र अस्त",
        "tithi": "तिथियाँ",
        "nakshatra": "नक्षत्र",
        "karana": "करण",
        "yoga": "योग",
        "day_horas": "दिवा होरा",
        "night_horas": "रात्रि होरा",
        "no_festivals": "आज कोई प्रमुख त्योहार नहीं",
    },
    event_labels={
        "name": "नाम",
        "start": "आरंभ",
        "end": "समाप्ति",
    },
    tithi_full=_extend_tithis(HINDI_SHUKLA_TITHIS, "अमावस्या"),
    nakshatra=[
        "अश्विनी",
        "भरणी",
        "कृत्तिका",
        "रोहिणी",
        "मृगशिरा",
        "आर्द्रा",
        "पुनर्वसु",
        "पुष्य",
        "आश्लेषा",
        "मघा",
        "पूर्व फाल्गुनी",
        "उत्तर फाल्गुनी",
        "हस्त",
        "चित्रा",
        "स्वाति",
        "विशाखा",
        "अनुराधा",
        "ज्येष्ठा",
        "मूला",
        "पूर्वाषाढ़ा",
        "उत्तराषाढ़ा",
        "श्रवण",
        "धनिष्ठा",
        "शतभिषा",
        "पूर्व भाद्रपदा",
        "उत्तर भाद्रपदा",
        "रेवती",
    ],
    paksha=["शुक्ल पक्ष", "कृष्ण पक्ष"],
    karana=[
        "बव",
        "बालव",
        "कौलव",
        "तैतिल",
        "गर्ज",
        "वणिज",
        "भद्रा",
        "शकुनि",
        "चतुष्पद",
        "नाग",
        "किंस्तुघ्न",
    ],
    yoga=[
        "विष्कंभ",
        "प्रीति",
        "आयुष्मान",
        "सौभाग्य",
        "शोभन",
        "अतिगंड",
        "सुकर्मा",
        "धृति",
        "शूल",
        "गंड",
        "वृद्धि",
        "ध्रुव",
        "व्याघात",
        "हर्षण",
        "वज्र",
        "सिद्धि",
        "व्यतीपात",
        "वरीयान",
        "परिघ",
        "शिव",
        "सिद्ध",
        "साध्य",
        "शुभ",
        "शुक्ल",
        "ब्रह्म",
        "इंद्र",
        "वैधृति",
    ],
    amanta_month=[
        "चैत्र",
        "वैशाख",
        "ज्येष्ठ",
        "आषाढ़",
        "श्रावण",
        "भाद्रपद",
        "आश्विन",
        "कार्तिक",
        "मार्गशीर्ष",
        "पौष",
        "माघ",
        "फाल्गुन",
    ],
    purnimanta_month=[
        "चैत्र",
        "वैशाख",
        "ज्येष्ठ",
        "आषाढ़",
        "श्रावण",
        "भाद्रपद",
        "आश्विन",
        "कार्तिक",
        "आग्रहायण",
        "पौष",
        "माघ",
        "फाल्गुन",
    ],
    saka_month=[
        "चैत्र",
        "वैशाख",
        "ज्येष्ठ",
        "आषाढ़",
        "श्रावण",
        "भाद्र",
        "आश्विन",
        "कार्तिक",
        "आग्रहायण",
        "पौष",
        "माघ",
        "फाल्गुन",
    ],
    weekday=[
        "सोमवार",
        "मंगलवार",
        "बुधवार",
        "गुरुवार",
        "शुक्रवार",
        "शनिवार",
        "रविवार",
    ],
    hora_planet=[
        "सूर्य",
        "शुक्र",
        "बुध",
        "चंद्र",
        "शनि",
        "गुरु",
        "मंगल",
    ],
    auspicious_labels=HINDI_AUSPICIOUS_LABELS,
    inauspicious_labels=HINDI_INAUSPICIOUS_LABELS,
)


# ---------------------------------------------------------------------------
# Tamil profile

TAMIL_SHUKLA_TITHIS = [
    "பிரதமை",
    "துவிதியை",
    "த்ரிதியை",
    "சதுர்த்தி",
    "பஞ்சமி",
    "ஷஷ்டி",
    "சப்தமி",
    "அஷ்டமி",
    "நவமி",
    "தசமி",
    "ஏகாதசி",
    "த்வாதசி",
    "திரயோதசி",
    "சதுர்தசி",
    "பௌர்ணமி",
]

TAMIL_AUSPICIOUS_LABELS = {
    "Abhijit Muhurat": "அபிஜித் முகூர்த்தம்",
    "Amrit Kaal": "அமிர்த காலம்",
    "Brahma Muhuratham": "பிரம்ம முகூர்த்தம்",
    "Pratah Sandhya": "பிரத: சந்த்யை",
    "Vijaya Muhurta": "விஜய முகூர்த்தம்",
    "Godhuli Muhurta": "கோதூலி முகூர்த்தம்",
    "Sayahna Sandhya": "சாயங்கால சந்த்யை",
    "Nishita Muhurta": "நிஷித முகூர்த்தம்",
}

TAMIL_INAUSPICIOUS_LABELS = {
    "Rahu Kalam": "ராகு காலம்",
    "Yamagandam": "யமகண்டம்",
    "Gulika Kalam": "குளிகை காலம்",
}

TAMIL_PROFILE = ProfileAssets(
    code="ta",
    language="Tamil",
    script="Tamil",
    section_titles={
        "date": "தேதி",
        "indian_civil": "இந்திய தேசிய நாட்காட்டி",
        "lunar_context": "சந்திர மாத தகவல்",
        "sun_moon": "சூரியன் & சந்திரன்",
        "core_panchang": "முக்கிய பஞ்சாங்கம்",
        "auspicious": "சுப நேரங்கள்",
        "inauspicious": "அசுப நேரங்கள்",
        "horas": "ஹோரைகள்",
        "festivals": "திருவிழாக்கள்",
    },
    field_labels={
        "year": "ஆண்டு",
        "month": "மாதம்",
        "day_number": "நாள்",
        "amanta_month": "அமாந்த மாதம்",
        "purnimanta_month": "பௌர்ணிமாந்த மாதம்",
        "paksha": "பக்ஷம்",
        "sunrise": "சூரிய உதயம்",
        "sunset": "சூரிய அஸ்தமனம்",
        "moonrise": "சந்திர உதயம்",
        "moonset": "சந்திர அஸ்தமனம்",
        "tithi": "திதிகள்",
        "nakshatra": "நட்சத்திரங்கள்",
        "karana": "கரணங்கள்",
        "yoga": "யோகங்கள்",
        "day_horas": "பகல் ஹோரைகள்",
        "night_horas": "இரவு ஹோரைகள்",
        "no_festivals": "இன்றைக்கு முக்கிய திருவிழா இல்லை",
    },
    event_labels={
        "name": "பெயர்",
        "start": "தொடக்கம்",
        "end": "முடிவு",
    },
    tithi_full=_extend_tithis(TAMIL_SHUKLA_TITHIS, "அமாவாசை"),
    nakshatra=[
        "அஸ்வினி",
        "பரணி",
        "கிருத்திகை",
        "ரோஹிணி",
        "மிருகசீரிடம்",
        "திருவாதிரை",
        "புனர்பூசம்",
        "பூசம்",
        "ஆயில்யம்",
        "மகம்",
        "பூரம்",
        "உத்திரம்",
        "ஹஸ்தம்",
        "சித்திரை",
        "சுவாதி",
        "பிசகם",
        "அனுஷம்",
        "கேட்டை",
        "மூலம்",
        "பூராடம்",
        "உத்திராடம்",
        "திருவோணம்",
        "அவிட்டம்",
        "சதயம்",
        "பூரட்டாதி",
        "உத்திரட்டாதி",
        "ரேவதி",
    ],
    paksha=["சுக்ல பக்ஷம்", "கிருஷ்ண பக்ஷம்"],
    karana=[
        "பவ",
        "பலவ",
        "கௌலவ",
        "தைதுல",
        "கரஜ",
        "வணிக",
        "பத்திரை",
        "சகுனி",
        "சதுஷ்பாத",
        "நாகம்",
        "கிம்ஸ்துக்ன",
    ],
    yoga=[
        "விஷ்கம்பம்",
        "பிரிதி",
        "ஆயுஷ்மான்",
        "சௌபாக்கியம்",
        "சோபனம்",
        "அதிகண்டம்",
        "சுகர்மா",
        "திரிதி",
        "சூலம்",
        "கண்டம்",
        "விருத்தி",
        "த்ருவம்",
        "வியாகாதம்",
        "ஹர்ஷணம்",
        "வஜ்ரம்",
        "சித்தி",
        "விதியபாதம்",
        "வரியான்",
        "பரிகம்",
        "சிவம்",
        "சித்தம்",
        "சாத்யம்",
        "சுபம்",
        "சுக்லம்",
        "பிரம்மம்",
        "இந்திரம்",
        "வைத்திருதி",
    ],
    amanta_month=[
        "சைத்ரம்",
        "வைசாகம்",
        "ஜ்யேஷ்டம்",
        "ஆசாதம்",
        "ஸ்ராவணம்",
        "பாத்ரபாதம்",
        "ஆச்சுவினி",
        "கார்த்திகம்",
        "மார்கழி",
        "தை",
        "மாசி",
        "பங்குனி",
    ],
    purnimanta_month=[
        "சைத்ரம்",
        "வைசாகம்",
        "ஜ்யேஷ்டம்",
        "ஆசாதம்",
        "ஸ்ராவணம்",
        "பாத்ரபாதம்",
        "ஆச்சுவினி",
        "கார்த்திகம்",
        "மார்கழி",
        "தை",
        "மாசி",
        "பங்குனி",
    ],
    saka_month=[
        "சைத்ர",
        "வைசாக",
        "ஜ்யேஷ்ட",
        "ஆசாத",
        "ஸ்ராவண",
        "பாத்ர",
        "ஆச்சுவின",
        "கார்த்திக",
        "அக்ரஹாயண",
        "பௌஷ",
        "மாக",
        "பல்குன",
    ],
    weekday=[
        "திங்கட்கிழமை",
        "செவ்வாய்க்கிழமை",
        "புதன்கிழமை",
        "வியாழக்கிழமை",
        "வெள்ளிக்கிழமை",
        "சனிக்கிழமை",
        "ஞாயிற்றுக்கிழமை",
    ],
    hora_planet=[
        "சூரியன்",
        "சுக்கிரன்",
        "புதன்",
        "சந்திரன்",
        "சனி",
        "குரு",
        "செவ்வாய்",
    ],
    auspicious_labels=TAMIL_AUSPICIOUS_LABELS,
    inauspicious_labels=TAMIL_INAUSPICIOUS_LABELS,
)


# ---------------------------------------------------------------------------
# Kannada profile

KANNADA_SHUKLA_TITHIS = [
    "ಪಾಡ್ಯಮಿ",
    "ದ್ವಿತೀಯ",
    "ತೃತೀಯ",
    "ಚತುರ್ಥೀ",
    "ಪಂಚಮಿ",
    "ಷಷ್ಠಿ",
    "ಸಪ್ತಮಿ",
    "ಅಷ್ಟಮಿ",
    "ನವಮಿ",
    "ದಶಮಿ",
    "ಏಕಾದಶಿ",
    "ದ್ವಾದಶಿ",
    "ತ್ರಯೋದಶಿ",
    "ಚತುರ್ದಶಿ",
    "ಪೌರ್ಣಮಿ",
]

KANNADA_AUSPICIOUS_LABELS = {
    "Abhijit Muhurat": "ಅಭಿಜಿತ್ ಮುಹೂರ್ತ",
    "Amrit Kaal": "ಅಮೃತ ಕಾಲ",
    "Brahma Muhuratham": "ಬ್ರಹ್ಮ ಮುಹೂರ್ತ",
    "Pratah Sandhya": "ಪ್ರಾತಃ ಸಂಧ್ಯಾ",
    "Vijaya Muhurta": "ವಿಜಯ ಮುಹೂರ್ತ",
    "Godhuli Muhurta": "ಗೋಧೂಲಿ ಮುಹೂರ್ತ",
    "Sayahna Sandhya": "ಸಾಯಂಕಾಲ ಸಂಧ್ಯಾ",
    "Nishita Muhurta": "ನಿಶೀಥ ಮುಹೂರ್ತ",
}

KANNADA_INAUSPICIOUS_LABELS = {
    "Rahu Kalam": "ರಾಹು ಕಾಲ",
    "Yamagandam": "ಯಮಗಂಡ",
    "Gulika Kalam": "ಗುಳಿಕ ಕಾಲ",
}

KANNADA_PROFILE = ProfileAssets(
    code="kn",
    language="Kannada",
    script="Kannada",
    section_titles={
        "date": "ದಿನಾಂಕ",
        "indian_civil": "ಭಾರತೀಯ ರಾಷ್ಟ್ರೀಯ ಕ್ಯಾಲೆಂಡರ್",
        "lunar_context": "ಚಂದ್ರ ಮಾಸ ಮಾಹಿತಿ",
        "sun_moon": "ಸೂರ್ಯ-ಚಂದ್ರೋದಯ",
        "core_panchang": "ಮೂಲ ಪಂಚಾಂಗ",
        "auspicious": "ಶುಭ ಸಮಯಗಳು",
        "inauspicious": "ಅಶುಭ ಸಮಯಗಳು",
        "horas": "ಹೋರಗಳು",
        "festivals": "ಹಬ್ಬಗಳು",
    },
    field_labels={
        "year": "ವರ್ಷ",
        "month": "ತಿಂಗಳು",
        "day_number": "ದಿನ",
        "amanta_month": "ಅಮಾನ್ತ ಮಾಸ",
        "purnimanta_month": "ಪೌರ್ನಿಮಾಂತ ಮಾಸ",
        "paksha": "ಪಕ್ಷ",
        "sunrise": "ಸೂರ್ಯೋದಯ",
        "sunset": "ಸೂರ್ಯಾಸ್ತ",
        "moonrise": "ಚಂದ್ರೋದಯ",
        "moonset": "ಚಂದ್ರಾಸ್ತ",
        "tithi": "ತಿಥಿಗಳು",
        "nakshatra": "ನಕ್ಷತ್ರಗಳು",
        "karana": "ಕರಣಗಳು",
        "yoga": "ಯೋಗಗಳು",
        "day_horas": "ಹಗಲು ಹೋರಗಳು",
        "night_horas": "ರಾತ್ರಿ ಹೋರಗಳು",
        "no_festivals": "ಇಂದು ಪ್ರಮುಖ ಹಬ್ಬಗಳಿಲ್ಲ",
    },
    event_labels={
        "name": "ಹೆಸರು",
        "start": "ಆರಂಭ",
        "end": "ಅಂತ್ಯ",
    },
    tithi_full=_extend_tithis(KANNADA_SHUKLA_TITHIS, "ಅಮಾವಾಸ್ಯೆ"),
    nakshatra=[
        "ಅಶ್ವಿನಿ",
        "ಭರಣಿ",
        "ಕೃತಿಕಾ",
        "ರೋಹಿಣಿ",
        "ಮೃಗಶಿರ",
        "ಆರ್ದ್ರ",
        "ಪುನರ್ವಸು",
        "ಪುಷ್ಯ",
        "ಆಶ್ಲೇಷಾ",
        "ಮಘ",
        "ಪೂರ್ವ ಫಾಲ್ಗುನಿ",
        "ಉತ್ತರ ಫಾಲ್ಗುನಿ",
        "ಹಸ್ತ",
        "ಚಿತ್ರಾ",
        "ಸ್ವಾತಿ",
        "ವಿಶಾಖ",
        "ಅನುರಾಧಾ",
        "ಜ್ಯೇಷ್ಠ",
        "ಮೂಲ",
        "ಪೂರ್ವ ಆಶಾಢ",
        "ಉತ್ತರ ಆಶಾಢ",
        "ಶ್ರವಣ",
        "ಧನಿಷ್ಠಾ",
        "ಶತಭಿಷ",
        "ಪೂರ್ವ ಭಾದ್ರಪದ",
        "ಉತ್ತರ ಭಾದ್ರಪದ",
        "ರೇವತಿ",
    ],
    paksha=["ಶುಕ್ಲ ಪಕ್ಷ", "ಕೃಷ್ಣ ಪಕ್ಷ"],
    karana=[
        "ಬವ",
        "ಬಾಲವ",
        "ಕೌಲವ",
        "ತೈತಿಲ",
        "ಗರಜ",
        "ವಣಿಜ",
        "ಭದ್ರ",
        "ಶಕುನಿ",
        "ಚತುಷ್ಪದ",
        "ನಾಗ",
        "ಕಿಂಸ್ತುಘ್ನ",
    ],
    yoga=[
        "ವಿಷ್ಕಂಭ",
        "ಪ್ರೀತಿ",
        "ಆಯುಷ್ಮಾನ್",
        "ಸೌಭಾಗ್ಯ",
        "ಶೋಭನ",
        "ಅತಿಗಂಡ",
        "ಸುಕರ್ಮ",
        "ಧೃತಿ",
        "ಶೂಲ",
        "ಗಂಡ",
        "ವೃದ್ಧಿ",
        "ಧ್ರುವ",
        "ವ್ಯಾಘಾತ",
        "ಹರ್ಷಣ",
        "ವಜ್ರ",
        "ಸಿದ್ಧಿ",
        "ವ್ಯತಿಪಾತ",
        "ವರಿಯಾನ್",
        "ಪರಿಘ",
        "ಶಿವ",
        "ಸಿದ್ಧ",
        "ಸಾಧ್ಯ",
        "ಶುಭ",
        "ಶುಕ್ಲ",
        "ಬ್ರಹ್ಮ",
        "ಇಂದ್ರ",
        "ವೈಧೃತಿ",
    ],
    amanta_month=[
        "ಚೈತ್ರ",
        "ವೈಶಾಖ",
        "ಜ್ಯೇಷ್ಠ",
        "ಆಷಾಢ",
        "ಶ್ರಾವಣ",
        "ಭಾದ್ರಪದ",
        "ಆಶ್ವಯುಜ",
        "ಕಾರ್ತಿಕ",
        "ಮಾರ್ಗಶಿರ",
        "ಪೌಷ",
        "ಮಾಘ",
        "ಫಾಲ್ಗುನ",
    ],
    purnimanta_month=[
        "ಚೈತ್ರ",
        "ವೈಶಾಖ",
        "ಜ್ಯೇಷ್ಠ",
        "ಆಷಾಢ",
        "ಶ್ರಾವಣ",
        "ಭಾದ್ರಪದ",
        "ಆಶ್ವಯುಜ",
        "ಕಾರ್ತಿಕ",
        "ಮಾರ್ಗಶಿರ",
        "ಪೌಷ",
        "ಮಾಘ",
        "ಫಾಲ್ಗುನ",
    ],
    saka_month=[
        "ಚೈತ್ರ",
        "ವೈಶಾಖ",
        "ಜ್ಯೇಷ್ಠ",
        "ಆಷಾಢ",
        "ಶ್ರಾವಣ",
        "ಭಾದ್ರ",
        "ಆಶ್ವಯುಜ",
        "ಕಾರ್ತಿಕ",
        "ಆಗ್ರಹಾಯಣ",
        "ಪೌಷ",
        "ಮಾಘ",
        "ಫಾಲ್ಗುನ",
    ],
    weekday=[
        "ಸೋಮವಾರ",
        "ಮಂಗಳವಾರ",
        "ಬುಧವಾರ",
        "ಗುರುವಾರ",
        "ಶುಕ್ರವಾರ",
        "ಶನಿವಾರ",
        "ಭಾನುವಾರ",
    ],
    hora_planet=[
        "ಸೂರ್ಯ",
        "ಶುಕ್ರ",
        "ಬುಧ",
        "ಚಂದ್ರ",
        "ಶನಿ",
        "ಗುರು",
        "ಮಂಗಳ",
    ],
    auspicious_labels=KANNADA_AUSPICIOUS_LABELS,
    inauspicious_labels=KANNADA_INAUSPICIOUS_LABELS,
)


# ---------------------------------------------------------------------------
# Bengali profile

BENGALI_SHUKLA_TITHIS = [
    "প্রতিপদা",
    "দ্বিতীয়া",
    "তৃতীয়া",
    "চতুর্থী",
    "পঞ্চমী",
    "ষষ্ঠী",
    "সপ্তমী",
    "অষ্টমী",
    "নবমী",
    "দশমী",
    "একাদশী",
    "দ্বাদশী",
    "ত্রयोদশী",
    "চতুর্দশী",
    "পূর্ণিমা",
]

BENGALI_AUSPICIOUS_LABELS = {
    "Abhijit Muhurat": "অভিজিৎ মুহূর্ত",
    "Amrit Kaal": "অমৃত কাল",
    "Brahma Muhuratham": "ব্রহ্ম মুহূর্ত",
    "Pratah Sandhya": "প্রাতঃ সন্ধ্যা",
    "Vijaya Muhurta": "বিজয় মুহূর্ত",
    "Godhuli Muhurta": "গোধূলি মুহূর্ত",
    "Sayahna Sandhya": "সায়ং সন্ধ্যা",
    "Nishita Muhurta": "নিশীথ মুহূর্ত",
}

BENGALI_INAUSPICIOUS_LABELS = {
    "Rahu Kalam": "রাহু কাল",
    "Yamagandam": "যমগণ্ড",
    "Gulika Kalam": "গুলিক কাল",
}

BENGALI_PROFILE = ProfileAssets(
    code="bn",
    language="Bengali",
    script="Bengali",
    section_titles={
        "date": "তারিখ",
        "indian_civil": "ভারতীয় জাতীয় পঞ্জিকা",
        "lunar_context": "চন্দ্র মাসের তথ্য",
        "sun_moon": "সূর্য ও চন্দ্রোদয়",
        "core_panchang": "মূল পঞ্চাঙ্গ",
        "auspicious": "শুভ সময়",
        "inauspicious": "অশুভ সময়",
        "horas": "ঘড়া",
        "festivals": "উৎসব",
    },
    field_labels={
        "year": "বর্ষ",
        "month": "মাস",
        "day_number": "দিন",
        "amanta_month": "অমান্ত মাস",
        "purnimanta_month": "পূর্ণিমান্ত মাস",
        "paksha": "পক্ষ",
        "sunrise": "সূর্যোদয়",
        "sunset": "সূর্যাস্ত",
        "moonrise": "চন্দ্রোদয়",
        "moonset": "চন্দ্রাস্ত",
        "tithi": "তিথি",
        "nakshatra": "নক্ষত্র",
        "karana": "করন",
        "yoga": "যোগ",
        "day_horas": "দিবস ঘড়া",
        "night_horas": "রাত্রি ঘড়া",
        "no_festivals": "আজ কোনও প্রধান উৎসব নেই",
    },
    event_labels={
        "name": "নাম",
        "start": "শুরু",
        "end": "সমাপ্ত",
    },
    tithi_full=_extend_tithis(BENGALI_SHUKLA_TITHIS, "অমাবস্যা"),
    nakshatra=[
        "অশ্বিনী",
        "ভরণী",
        "কৃত্তিকা",
        "রোহিণী",
        "মৃগশিরা",
        "আর্দ্রা",
        "পুনর্বসু",
        "পুষ্যা",
        "আশ্লেষা",
        "মঘা",
        "পূর্বা ফল্গুনী",
        "উত্তরা ফল্গুনী",
        "হস্তা",
        "চিত্তা",
        "স্বাতী",
        "বিশাখা",
        "অনুরাধা",
        "জ্যেষ্ঠা",
        "মূলা",
        "পূর্বাষাঢ়া",
        "উত্তরাষাঢ়া",
        "শ্রবণ",
        "ধনিষ্ঠা",
        "শতভিষা",
        "পূর্ব ভাদ্রপদা",
        "উত্তর ভাদ্রপদা",
        "রেভতী",
    ],
    paksha=["শুক্ল পক্ষ", "কৃষ্ণ পক্ষ"],
    karana=[
        "বব",
        "বলব",
        "কৌলব",
        "তৈতিল",
        "গারজ",
        "বণিক",
        "ভদ্রা",
        "শকুনি",
        "চতুষ্পদ",
        "নাগ",
        "কিমস্তুঘ্ন",
    ],
    yoga=[
        "বিশ্কম্ভ",
        "প্রীতি",
        "আয়ুষ্মান",
        "সৌভাগ্য",
        "শোভন",
        "অতিগণ্ড",
        "সুকর্মা",
        "ধৃতি",
        "শূল",
        "গণ্ড",
        "বৃদ্ধি",
        "ধ্রুব",
        "ব্যাঘাত",
        "হর্ষণ",
        "বজ্র",
        "সিদ্ধি",
        "ব্যতিপাত",
        "বরিয়ান",
        "পরিঘ",
        "শিব",
        "সিদ্ধ",
        "সাধ্য",
        "শুভ",
        "শুক্ল",
        "ব্রহ্ম",
        "ইন্দ্র",
        "বৈধৃতি",
    ],
    amanta_month=[
        "চৈত্র",
        "বৈশাখ",
        "জ্যৈষ্ঠ",
        "আষাঢ়",
        "শ্রাবণ",
        "ভাদ্র",
        "আশ্বিন",
        "কার্ত্তিক",
        "অগ্রহায়ণ",
        "পৌষ",
        "মাঘ",
        "ফাল্গুন",
    ],
    purnimanta_month=[
        "চৈত্র",
        "বৈশাখ",
        "জ্যৈষ্ঠ",
        "আষাঢ়",
        "শ্রাবণ",
        "ভাদ্র",
        "আশ্বিন",
        "কার্ত্তিক",
        "অগ্রহায়ণ",
        "পৌষ",
        "মাঘ",
        "ফাল্গুন",
    ],
    saka_month=[
        "চৈত্র",
        "বৈশাখ",
        "জ্যৈষ্ঠ",
        "আষাঢ়",
        "শ্রাবণ",
        "ভাদ্র",
        "আশ্বিন",
        "কার্ত্তিক",
        "অগ্রহায়ণ",
        "পৌষ",
        "মাঘ",
        "ফাল্গুন",
    ],
    weekday=[
        "সোমবার",
        "মঙ্গলবার",
        "বুধবার",
        "বৃহস্পতিবার",
        "শুক্রবার",
        "শনিবার",
        "রবিবার",
    ],
    hora_planet=[
        "সূর্য",
        "শুক্র",
        "বুধ",
        "চন্দ্র",
        "শনি",
        "বৃহস্পতি",
        "মঙ্গল",
    ],
    auspicious_labels=BENGALI_AUSPICIOUS_LABELS,
    inauspicious_labels=BENGALI_INAUSPICIOUS_LABELS,
)


# ---------------------------------------------------------------------------
# Gujarati profile

GUJARATI_SHUKLA_TITHIS = [
    "પ્રથમ",
    "બીજ",
    "ત્રીજ",
    "ચોથ",
    "પાંચમ",
    "છઠ્ઠ",
    "સપ્તમી",
    "અષ્ઠમી",
    "નવમી",
    "દશમી",
    "એકાદશી",
    "દ્વાદશી",
    "ત્રયોદશી",
    "ચતુર્દશી",
    "પૂનમ",
]

GUJARATI_AUSPICIOUS_LABELS = {
    "Abhijit Muhurat": "અભિજીત મુહૂર્ત",
    "Amrit Kaal": "અમૃત કાલ",
    "Brahma Muhuratham": "બ્રહ્મ મુહૂર્ત",
    "Pratah Sandhya": "પ્રાતઃ સંધ્યા",
    "Vijaya Muhurta": "વિજય મુહૂર્ત",
    "Godhuli Muhurta": "ગોધૂલી મુહૂર્ત",
    "Sayahna Sandhya": "સાંજ સંધ્યા",
    "Nishita Muhurta": "નિશીથ મુહૂર્ત",
}

GUJARATI_INAUSPICIOUS_LABELS = {
    "Rahu Kalam": "રાહુ કાળ",
    "Yamagandam": "યમગંડ",
    "Gulika Kalam": "ગુલિક કાળ",
}

GUJARATI_PROFILE = ProfileAssets(
    code="gu",
    language="Gujarati",
    script="Gujarati",
    section_titles={
        "date": "તારીખ",
        "indian_civil": "ભારતીય રાષ્ટ્રીય પંચાંગ",
        "lunar_context": "ચંદ્ર માસ વિગતો",
        "sun_moon": "સૂર્ય-ચંદ્રોદય",
        "core_panchang": "મુખ્ય પંચાંગ",
        "auspicious": "શુભ મુહૂર્ત",
        "inauspicious": "અશુભ સમય",
        "horas": "હોરા",
        "festivals": "ઉત્સવો",
    },
    field_labels={
        "year": "વર્ષ",
        "month": "માસ",
        "day_number": "દિવસ",
        "amanta_month": "અમાંત માસ",
        "purnimanta_month": "પૂર્ણિમાંત માસ",
        "paksha": "પક્ષ",
        "sunrise": "સૂર્યોદય",
        "sunset": "સૂર્યાસ્ત",
        "moonrise": "ચંદ્રોદય",
        "moonset": "ચંદ્રાસ્ત",
        "tithi": "તિતિઓ",
        "nakshatra": "નક્ષત્ર",
        "karana": "કરણ",
        "yoga": "યોગ",
        "day_horas": "દિવસના હોરા",
        "night_horas": "રાત્રિના હોરા",
        "no_festivals": "આજે કોઈ મુખ્ય ઉત્સવ નથી",
    },
    event_labels={
        "name": "નામ",
        "start": "આરંભ",
        "end": "સમાપ્તિ",
    },
    tithi_full=_extend_tithis(GUJARATI_SHUKLA_TITHIS, "અમાવસ્યા"),
    nakshatra=[
        "અશ્વિની",
        "ભરણિ",
        "કૃતિકા",
        "રોહિણી",
        "મૃગશિર્ષ",
        "આર્દ્રા",
        "પુનર્વસુ",
        "પુષ્ય",
        "આશ્રેષા",
        "માઘા",
        "પૂર્વ ફાલ્ગુની",
        "ઉત્તર ફાલ્ગુની",
        "હસ્ત",
        "ચિત્રા",
        "સ્વાતી",
        "વિશાખા",
        "અનુરાધા",
        "જયેષ્ઠા",
        "મૂળ",
        "પૂર્વાષાઢા",
        "ઉત્તરાષાઢા",
        "શ્રવણ",
        "ધનિષ્ઠા",
        "શતભિષા",
        "પૂર્વ ભાદ્રપદા",
        "ઉત્તર ભાદ્રપદા",
        "રેવતી",
    ],
    paksha=["શુક્લ પક્ષ", "કૃષ્ણ પક્ષ"],
    karana=[
        "બવ",
        "બાલવ",
        "કૌલવ",
        "તૈતિલ",
        "ગરજ",
        "વણિજ",
        "ભદ્રા",
        "શકુની",
        "ચતુષ્પદ",
        "નાગ",
        "કિંસ્તુઘ્ન",
    ],
    yoga=[
        "વિશ્કંભ",
        "પ્રીતિ",
        "આયુષ્માન",
        "સૌભાગ્ય",
        "શોભન",
        "અતિગંડ",
        "સુકર્મા",
        "ધૃતિ",
        "શૂલ",
        "ગંડ",
        "વૃદ્ધિ",
        "ધ્રુવ",
        "વ્યાઘાત",
        "હર્ષણ",
        "વજ્ર",
        "સિદ્ધિ",
        "વ્યતિપાત",
        "વરિયાન",
        "પરીઘ",
        "શિવ",
        "સિદ્ધ",
        "સાધ્ય",
        "શુભ",
        "શુક્લ",
        "બ્રહ્મ",
        "ઇન્દ્ર",
        "વૈધૃતિ",
    ],
    amanta_month=[
        "ચૈત્ર",
        "વૈશાખ",
        "જેઠ",
        "આષાઢ",
        "શ્રાવણ",
        "ભાદરવા",
        "આસો",
        "કારતક",
        "માર્ગશીર્ષ",
        "પોષ",
        "માઘ",
        "ફાલ્ગુન",
    ],
    purnimanta_month=[
        "ચૈત્ર",
        "વૈશાખ",
        "જેઠ",
        "આષાઢ",
        "શ્રાવણ",
        "ભાદરવા",
        "આસો",
        "કારતક",
        "માર્ગશીર્ષ",
        "પોષ",
        "માઘ",
        "ફાલ્ગુન",
    ],
    saka_month=[
        "ચૈત્ર",
        "વૈશાખ",
        "જેઠ",
        "આષાઢ",
        "શ્રાવણ",
        "ભાદ્ર",
        "આસો",
        "કારતક",
        "અગ્રહાયણ",
        "પોષ",
        "માઘ",
        "ફાલ્ગુન",
    ],
    weekday=[
        "સોમવાર",
        "મંગળવાર",
        "બુધવાર",
        "ગુરુવાર",
        "શુક્રવાર",
        "શનિવાર",
        "રવિવાર",
    ],
    hora_planet=[
        "સૂર્ય",
        "શુક્ર",
        "બુધ",
        "ચંદ્ર",
        "શનિ",
        "ગુરુ",
        "મંગળ",
    ],
    auspicious_labels=GUJARATI_AUSPICIOUS_LABELS,
    inauspicious_labels=GUJARATI_INAUSPICIOUS_LABELS,
)


PROFILE_REGISTRY: Dict[str, ProfileAssets] = {
    profile.code: profile
    for profile in [
        ENGLISH_PROFILE,
        TELUGU_PROFILE,
        HINDI_PROFILE,
        TAMIL_PROFILE,
        KANNADA_PROFILE,
        BENGALI_PROFILE,
        GUJARATI_PROFILE,
    ]
}


def get_profile_assets(code: str) -> ProfileAssets:
    return PROFILE_REGISTRY.get(code, ENGLISH_PROFILE)


def list_profiles() -> List[ProfileAssets]:
    return list(PROFILE_REGISTRY.values())


