# Generated by Django 4.2.16 on 2025-11-08 16:46

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import panchang.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('festival_name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of the name', max_length=250, unique=True)),
                ('type', models.CharField(max_length=100)),
                ('importance', models.CharField(choices=[('Major', 'Major'), ('Moderate', 'Moderate'), ('Minor', 'Minor')], default='Minor', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Rich text content with image upload support', null=True)),
                ('image', models.ImageField(blank=True, help_text='Main image for the festival', null=True, upload_to=panchang.utils.festival_image_upload_path)),
                ('image_thumb', models.CharField(blank=True, help_text='Path to thumbnail (300x200)', max_length=500, null=True)),
                ('image_medium', models.CharField(blank=True, help_text='Path to medium size (800x600)', max_length=500, null=True)),
                ('image_large', models.CharField(blank=True, help_text='Path to large size (1600x900)', max_length=500, null=True)),
                ('month', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('paksha', models.CharField(blank=True, max_length=20, null=True)),
                ('tithi', models.CharField(blank=True, max_length=50, null=True)),
                ('nakshatra', models.CharField(blank=True, max_length=50, null=True)),
                ('solar_event', models.CharField(blank=True, max_length=200, null=True)),
                ('calculation_type', models.CharField(choices=[('lunar', 'Lunar'), ('solar', 'Solar'), ('unspecified', 'Unspecified')], default='lunar', max_length=20)),
                ('regions', models.JSONField(default=list, help_text='List of regions where festival is observed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'festivals',
                'ordering': ['festival_name'],
            },
        ),
        migrations.CreateModel(
            name='FestivalGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Wallpaper image', upload_to=panchang.utils.gallery_image_upload_path)),
                ('image_alt', models.CharField(blank=True, help_text='Alt text for image', max_length=255)),
                ('caption', models.CharField(blank=True, help_text='Image caption', max_length=500)),
                ('image_thumb', models.CharField(blank=True, help_text='Path to thumbnail (300x200)', max_length=500, null=True)),
                ('image_medium', models.CharField(blank=True, help_text='Path to medium size (800x600)', max_length=500, null=True)),
                ('image_large', models.CharField(blank=True, help_text='Path to large size (1600x900)', max_length=500, null=True)),
                ('display_order', models.IntegerField(default=0, help_text='Order for displaying images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Festival Gallery Images',
                'db_table': 'festival_gallery',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportantDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_id', models.IntegerField(db_index=True, default=0, help_text='Sequential ID for sorting from first to last record')),
                ('date', models.CharField(db_index=True, help_text="Format: DD Month, e.g., '01 January'", max_length=20)),
                ('day_name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of the name', max_length=250, unique=True)),
                ('type_of', models.CharField(max_length=100)),
                ('importance', models.CharField(choices=[('Major', 'Major'), ('Moderate', 'Moderate'), ('Minor', 'Minor')], default='Minor', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Rich text content with image upload support', null=True)),
                ('image', models.ImageField(blank=True, help_text='Main image for the important day', null=True, upload_to=panchang.utils.important_day_image_upload_path)),
                ('image_thumb', models.CharField(blank=True, help_text='Path to thumbnail (300x200)', max_length=500, null=True)),
                ('image_medium', models.CharField(blank=True, help_text='Path to medium size (800x600)', max_length=500, null=True)),
                ('image_large', models.CharField(blank=True, help_text='Path to large size (1600x900)', max_length=500, null=True)),
                ('is_holiday', models.CharField(blank=True, choices=[('india_holiday', 'India Holiday'), ('state_holiday', 'State Holiday'), ('multi_state_holiday', 'Multi-State Holiday'), ('observance_only', 'Observance Only')], max_length=30, null=True)),
                ('regions', models.JSONField(default=list, help_text='List of regions where day is observed')),
                ('calendar_type', models.CharField(default='gregorian', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'important_days',
                'ordering': ['sequence_id', 'date', 'day_name'],
            },
        ),
        migrations.CreateModel(
            name='ImportantDayGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Wallpaper image', upload_to=panchang.utils.gallery_image_upload_path)),
                ('image_alt', models.CharField(blank=True, help_text='Alt text for image', max_length=255)),
                ('caption', models.CharField(blank=True, help_text='Image caption', max_length=500)),
                ('image_thumb', models.CharField(blank=True, help_text='Path to thumbnail (300x200)', max_length=500, null=True)),
                ('image_medium', models.CharField(blank=True, help_text='Path to medium size (800x600)', max_length=500, null=True)),
                ('image_large', models.CharField(blank=True, help_text='Path to large size (1600x900)', max_length=500, null=True)),
                ('display_order', models.IntegerField(default=0, help_text='Order for displaying images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('important_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='panchang.importantday')),
            ],
            options={
                'verbose_name_plural': 'Important Day Gallery Images',
                'db_table': 'important_day_gallery',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='importantday',
            index=models.Index(fields=['sequence_id'], name='important_d_sequenc_fac9b1_idx'),
        ),
        migrations.AddIndex(
            model_name='importantday',
            index=models.Index(fields=['slug'], name='important_d_slug_bfc086_idx'),
        ),
        migrations.AddIndex(
            model_name='importantday',
            index=models.Index(fields=['date'], name='important_d_date_2442b3_idx'),
        ),
        migrations.AddIndex(
            model_name='importantday',
            index=models.Index(fields=['day_name'], name='important_d_day_nam_315969_idx'),
        ),
        migrations.AddIndex(
            model_name='importantday',
            index=models.Index(fields=['is_holiday'], name='important_d_is_holi_97e8c8_idx'),
        ),
        migrations.AddField(
            model_name='festivalgallery',
            name='festival',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='panchang.festival'),
        ),
        migrations.AddIndex(
            model_name='festival',
            index=models.Index(fields=['festival_name'], name='festivals_festiva_7c601f_idx'),
        ),
        migrations.AddIndex(
            model_name='festival',
            index=models.Index(fields=['slug'], name='festivals_slug_3dba86_idx'),
        ),
        migrations.AddIndex(
            model_name='festival',
            index=models.Index(fields=['month', 'tithi', 'paksha'], name='festivals_month_2a8ef8_idx'),
        ),
        migrations.AddIndex(
            model_name='festival',
            index=models.Index(fields=['calculation_type'], name='festivals_calcula_1e95bf_idx'),
        ),
    ]
