# Generated by Django 4.2.16 on 2025-11-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panchang', '0002_add_image_thumbnails_and_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='image_hash',
            field=models.CharField(blank=True, db_index=True, help_text='MD5 hash of image content for duplicate detection', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='festivalgallery',
            name='image_hash',
            field=models.CharField(blank=True, db_index=True, help_text='MD5 hash of image content for duplicate detection', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='importantday',
            name='image_hash',
            field=models.CharField(blank=True, db_index=True, help_text='MD5 hash of image content for duplicate detection', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='importantdaygallery',
            name='image_hash',
            field=models.CharField(blank=True, db_index=True, help_text='MD5 hash of image content for duplicate detection', max_length=64, null=True),
        ),
    ]
