# Generated by Django 4.2.16 on 2025-11-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panchang', '0003_add_image_hash_duplicate_detection'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='observation',
            field=models.TextField(blank=True, help_text='Admin observation/notes about this festival', null=True),
        ),
    ]
