# Generated by Django 4.2.16 on 2025-11-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panchang', '0004_festival_observation'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='festival',
                    name='festival_dates',
                    field=models.JSONField(blank=True, default=dict, help_text="JSON object storing festival dates: {year: [{'date': 'YYYY-MM-DD', 'time': 'HH:MM AM/PM', 'datetime': 'ISO'}]}", null=True),
                ),
            ],
            database_operations=[]
        ),
    ]
