# Generated by Django 4.2.16 on 2025-12-13 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panchang', '0005_festival_festival_dates'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='festival',
                    name='image_large',
                ),
                migrations.RemoveField(
                    model_name='festival',
                    name='image_medium',
                ),
                migrations.RemoveField(
                    model_name='festival',
                    name='image_thumb',
                ),
                migrations.RemoveField(
                    model_name='festivalgallery',
                    name='image_large',
                ),
                migrations.RemoveField(
                    model_name='festivalgallery',
                    name='image_medium',
                ),
                migrations.RemoveField(
                    model_name='festivalgallery',
                    name='image_thumb',
                ),
                migrations.RemoveField(
                    model_name='importantday',
                    name='image_large',
                ),
                migrations.RemoveField(
                    model_name='importantday',
                    name='image_medium',
                ),
                migrations.RemoveField(
                    model_name='importantday',
                    name='image_thumb',
                ),
                migrations.RemoveField(
                    model_name='importantdaygallery',
                    name='image_large',
                ),
                migrations.RemoveField(
                    model_name='importantdaygallery',
                    name='image_medium',
                ),
                migrations.RemoveField(
                    model_name='importantdaygallery',
                    name='image_thumb',
                ),
            ],
            database_operations=[]
        ),
    ]
