# Generated by Django 4.2.16 on 2026-02-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panchang', '0006_remove_festival_image_large_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanchangData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(help_text='Date in YYYY-MM-DD format usually', max_length=50, unique=True)),
                ('day', models.CharField(help_text='Day of the week (e.g., Guru, Shukra)', max_length=50)),
                ('lunar_month', models.CharField(help_text='Lunar Month (e.g., Pushya)', max_length=100)),
                ('paksha', models.CharField(help_text='Paksha (e.g., Shuddha)', max_length=50)),
                ('thithi', models.CharField(help_text='Thithi (e.g., Trayodashi)', max_length=100)),
                ('thithi_end', models.CharField(help_text='Thithi End Time', max_length=50)),
                ('nakshatram', models.CharField(help_text='Nakshatram (e.g., Rohini)', max_length=100)),
                ('nakshatram_end', models.CharField(help_text='Nakshatram End Time', max_length=50)),
                ('varjyam_time', models.CharField(help_text='Varjyam Time Range', max_length=100)),
                ('durmuhurtham_1', models.CharField(help_text='Durmuhurtham 1 Time Range', max_length=100)),
                ('durmuhurtham_2', models.CharField(blank=True, help_text='Durmuhurtham 2 Time Range', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Panchang Data',
                'db_table': 'panchang_data',
                'ordering': ['date'],
            },
        ),
    ]
