# Generated by Django 4.2.16 on 2026-02-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panchang', '0008_panchangjsonexport'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='panchangdata',
                    name='abhijit_muhurtham',
                    field=models.CharField(blank=True, help_text='Abhijit Muhurtham', max_length=50, null=True),
                ),
                migrations.AddField(
                    model_name='panchangdata',
                    name='amrita_kalam',
                    field=models.CharField(blank=True, help_text='Amrita Kalam', max_length=50, null=True),
                ),
                migrations.AddField(
                    model_name='panchangdata',
                    name='brahma_muhurtham',
                    field=models.CharField(blank=True, help_text='Brahma Muhurtham', max_length=50, null=True),
                ),
                migrations.AddField(
                    model_name='panchangdata',
                    name='godhuli_muhurtham',
                    field=models.CharField(blank=True, help_text='Godhuli Muhurtham', max_length=50, null=True),
                ),
                migrations.AddField(
                    model_name='panchangdata',
                    name='gulika_kalam',
                    field=models.CharField(blank=True, help_text='Gulika Kalam', max_length=50, null=True),
                ),
                migrations.AddField(
                    model_name='panchangdata',
                    name='moonrise',
                    field=models.CharField(blank=True, help_text='Moonrise Time', max_length=50, null=True),
                ),
                migrations.AddField(
                    model_name='panchangdata',
                    name='moonset',
                    field=models.CharField(blank=True, help_text='Moonset Time', max_length=50, null=True),
                ),
                migrations.AddField(
                    model_name='panchangdata',
                    name='nishita_muhurtham',
                    field=models.CharField(blank=True, help_text='Nishita Muhurtham', max_length=50, null=True),
                ),
                migrations.AddField(
                    model_name='panchangdata',
                    name='pratah_sandhya',
                    field=models.CharField(blank=True, help_text='Pratah Sandhya', max_length=50, null=True),
                ),
                migrations.AddField(
                    model_name='panchangdata',
                    name='rahu_kalam',
                    field=models.CharField(blank=True, help_text='Rahu Kalam', max_length=50, null=True),
                ),
                migrations.AddField(
                    model_name='panchangdata',
                    name='sayam_sandhya',
                    field=models.CharField(blank=True, help_text='Sayam Sandhya', max_length=50, null=True),
                ),
                migrations.AddField(
                    model_name='panchangdata',
                    name='sunrise',
                    field=models.CharField(blank=True, help_text='Sunrise Time', max_length=50, null=True),
                ),
                migrations.AddField(
                    model_name='panchangdata',
                    name='sunset',
                    field=models.CharField(blank=True, help_text='Sunset Time', max_length=50, null=True),
                ),
                migrations.AddField(
                    model_name='panchangdata',
                    name='vijaya_muhurtham',
                    field=models.CharField(blank=True, help_text='Vijaya Muhurtham', max_length=50, null=True),
                ),
                migrations.AddField(
                    model_name='panchangdata',
                    name='yamagandam',
                    field=models.CharField(blank=True, help_text='Yamagandam', max_length=50, null=True),
                ),
            ],
            database_operations=[]
        ),
    ]
