# Generated by Django 4.2.16 on 2026-02-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panchang', '0009_panchangdata_abhijit_muhurtham_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panchangdata',
            name='day',
        ),
        migrations.RemoveField(
            model_name='panchangdata',
            name='gulika_kalam',
        ),
        migrations.RemoveField(
            model_name='panchangdata',
            name='rahu_kalam',
        ),
        migrations.RemoveField(
            model_name='panchangdata',
            name='yamagandam',
        ),
        migrations.AddField(
            model_name='panchangdata',
            name='festivals',
            field=models.TextField(blank=True, help_text='Comma-separated list of festivals', null=True),
        ),
    ]
