# Generated by Django 4.2.16 on 2026-02-02 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panchang', '0010_remove_panchangdata_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panchangdata',
            name='festivals',
        ),
        migrations.CreateModel(
            name='PanchangDailyFestival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('festival_name', models.CharField(help_text='Display name for the festival on this day', max_length=200)),
                ('festival_reference', models.ForeignKey(blank=True, help_text='Reference to the master Festival record', null=True, on_delete=django.db.models.deletion.SET_NULL, to='panchang.festival')),
                ('panchang_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_festivals', to='panchang.panchangdata')),
            ],
            options={
                'verbose_name': 'Panchang Daily Festival',
                'verbose_name_plural': 'Panchang Daily Festivals',
                'db_table': 'panchang_daily_festivals',
            },
        ),
    ]
