# Generated by Django 4.2.16 on 2026-02-02 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panchang', '0011_remove_panchangdata_festivals_panchangdailyfestival'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='panchangdailyfestival',
            table='panchang_data_daily_festivals',
        ),
    ]
