# Generated by Django 4.2.16 on 2025-11-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='audio_images/'),
        ),
    ]
