import json
import os
import glob
from django.core.management.base import BaseCommand
from panchang.models import PanchangData
from datetime import datetime

class Command(BaseCommand):
    help = 'Imports Panchang data from JSON files generated by the v2 calculator'

    def add_arguments(self, parser):
        parser.add_argument('json_dir', type=str, help='Path to the directory containing JSON files')

    def handle(self, *args, **options):
        json_dir = options['json_dir']
        
        # Find all JSON files in the directory
        json_files = glob.glob(os.path.join(json_dir, '*.json'))
        
        if not json_files:
            self.stdout.write(self.style.WARNING(f'No JSON files found in {json_dir}'))
            return

        self.stdout.write(self.style.SUCCESS(f'Found {len(json_files)} JSON files. Starting import...'))
        
        count = 0
        updated_count = 0
        
        for file_path in json_files:
            try:
                with open(file_path, 'r', encoding='utf-8') as f:
                    data = json.load(f)
                
                date_str = data.get('date')
                if not date_str:
                    continue
                    
                # Parse sections to find data
                sections = data.get('sections', [])
                
                # --- 1. Basic Info (Month, etc.) - SKIPPED AS PER REQUEST ---
                # lunar_month = ""
                
                # --- 2. Sun/Moon Rise/Set ---
                sunrise = None
                sunset = None
                moonrise = None
                moonset = None
                
                for section in sections:
                    if section.get('title') == "సూర్య చంద్రోదయాలు":
                        for item in section.get('items', []):
                            label = item.get('label')
                            value = item.get('value')
                            if label == "సూర్యోదయం": sunrise = value
                            elif label == "సూర్యాస్తమయం": sunset = value
                            elif label == "చంద్రోదయం": moonrise = value
                            elif label == "చంద్రాస్తమయం": moonset = value

                # --- 3. Tithi & Nakshatra & Paksha - SKIPPED AS PER REQUEST ---
                # thithi = ""
                # thithi_end = ""
                # nakshatram = ""
                # nakshatram_end = ""
                # paksha = ""

                # --- 4. Auspicious ---
                auspicious = {}
                for section in sections:
                    if section.get('title') == "శుభ సమయాలు":
                        for item in section.get('items', []):
                            label = item.get('label')
                            value = item.get('value')
                            if label == "అభిజిత్ ముహూర్తం": auspicious['abhijit_muhurtham'] = value
                            elif label == "అమృత కాలం": auspicious['amrita_kalam'] = value
                            elif label == "బ్రహ్మ ముహూర్తం": auspicious['brahma_muhurtham'] = value
                            elif label == "ప్రాతః సాంధ్య": auspicious['pratah_sandhya'] = value
                            elif label == "విజయ ముహూర్తం": auspicious['vijaya_muhurtham'] = value
                            elif label == "గోదూలి ముహూర్తం": auspicious['godhuli_muhurtham'] = value
                            elif label == "సాయంసాంధ్య": auspicious['sayam_sandhya'] = value
                            elif label == "నిశీత ముహూర్తం": auspicious['nishita_muhurtham'] = value

                # --- 5. Inauspicious (SKIPPED) ---
                # inauspicious = {}
                
                # Calculate Day of Week
                dt = datetime.strptime(date_str, "%Y-%m-%d")
                days_map = {0: "Somavaram", 1: "Mangalavaram", 2: "Budhavaram", 3: "Guruvaram", 4: "Shukravaram", 5: "Shanivaram", 6: "Bhanuvaram"}
                day_name = days_map.get(dt.weekday(), dt.strftime("%A"))


                # Update ONLY requested fields
                # Use get_or_create to ensure record exists, then update specific fields
                # This prevents overwriting Tithi/Nakshatra if they exist (or leaves them empty if new)
                obj, created = PanchangData.objects.get_or_create(date=date_str)
                
                obj.sunrise = sunrise
                obj.sunset = sunset
                obj.moonrise = moonrise
                obj.moonset = moonset
                
                obj.abhijit_muhurtham = auspicious.get('abhijit_muhurtham')
                obj.amrita_kalam = auspicious.get('amrita_kalam')
                obj.brahma_muhurtham = auspicious.get('brahma_muhurtham')
                obj.pratah_sandhya = auspicious.get('pratah_sandhya')
                obj.vijaya_muhurtham = auspicious.get('vijaya_muhurtham')
                obj.godhuli_muhurtham = auspicious.get('godhuli_muhurtham')
                obj.sayam_sandhya = auspicious.get('sayam_sandhya')
                obj.nishita_muhurtham = auspicious.get('nishita_muhurtham')
                
                obj.save()
                
                if created:
                    count += 1
                else:
                    updated_count += 1
                    
            except Exception as e:
                self.stderr.write(f"Error processing {file_path}: {e}")

        self.stdout.write(self.style.SUCCESS(f'Successfully imported {count} new records and updated {updated_count} records.'))
