# Generated by Django 4.2.16 on 2025-12-13 10:14

from django.db import migrations, models
import mobileapp_settings.models
import panchang.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to=panchang.utils.carousel_image_upload_path)),
                ('image_hash', models.CharField(blank=True, db_index=True, help_text='MD5 hash of image content for duplicate detection', max_length=64, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('order', models.IntegerField(default=0, help_text='The order in which the image should be displayed.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Carousel Images',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Unique identifier for this setting (e.g., 'site_title', 'hero_image')", max_length=100, unique=True)),
                ('value_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('url', 'URL'), ('number', 'Number'), ('boolean', 'Boolean')], default='text', help_text='Type of value stored in this setting', max_length=50)),
                ('text_value', models.TextField(blank=True, help_text='Text value', null=True)),
                ('image_value', models.ImageField(blank=True, help_text='Image value', null=True, upload_to=mobileapp_settings.models.site_setting_image_upload_path)),
                ('number_value', models.DecimalField(blank=True, decimal_places=10, help_text='Numeric value', max_digits=20, null=True)),
                ('boolean_value', models.BooleanField(blank=True, default=False, help_text='Boolean value', null=True)),
                ('url_value', models.URLField(blank=True, help_text='URL value', null=True)),
                ('description', models.TextField(blank=True, help_text='Description or help text for this setting', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this setting is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
