# Generated by Django 4.2.16

from django.db import migrations, models
import django.db.models.deletion


def delete_wallpapers_without_category_or_subcategory(apps, schema_editor):
    """Delete any wallpapers that don't have both category and subcategory"""
    Wallpaper = apps.get_model('wallpaper_manager', 'Wallpaper')
    # Delete wallpapers without category or subcategory
    Wallpaper.objects.filter(category__isnull=True).delete()
    Wallpaper.objects.filter(subcategory__isnull=True).delete()


def reverse_delete(apps, schema_editor):
    """Reverse migration - nothing to do"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper_manager', '0001_initial'),
    ]

    operations = [
        # First, delete any wallpapers without both category and subcategory
        migrations.RunPython(
            delete_wallpapers_without_category_or_subcategory,
            reverse_delete,
        ),
        # Change category to required (CASCADE, not nullable)
        migrations.AlterField(
            model_name='wallpaper',
            name='category',
            field=models.ForeignKey(
                help_text='Main category (required)',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='wallpapers',
                to='wallpaper_manager.category'
            ),
        ),
        # Change subcategory to required (CASCADE, not nullable)
        migrations.AlterField(
            model_name='wallpaper',
            name='subcategory',
            field=models.ForeignKey(
                help_text='Sub category (required)',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='wallpapers',
                to='wallpaper_manager.subcategory'
            ),
        ),
    ]
