# Generated by Django 4.2.16 on 2025-11-26 22:27

from django.db import migrations, models
import django.db.models.deletion


def check_and_migrate_data(apps, schema_editor):
    """Safely migrate data if tables exist"""
    db_alias = schema_editor.connection.alias
    Wallpaper = apps.get_model('wallpaper_manager', 'Wallpaper')
    Category = apps.get_model('wallpaper_manager', 'Category')
    
    # Check if wallpaper table exists by trying to count
    try:
        Wallpaper.objects.using(db_alias).count()
    except:
        # Table doesn't exist, skip data migration
        return


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper_manager', '0003_require_category_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent category (null for main categories)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='wallpaper_manager.category'),
        ),
        migrations.RunPython(check_and_migrate_data, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='wallpaper',
            name='subcategory',
        ),
        migrations.AlterField(
            model_name='wallpaper',
            name='category',
            field=models.ForeignKey(help_text='Category (must be a subcategory - category with parent)', on_delete=django.db.models.deletion.CASCADE, related_name='wallpapers', to='wallpaper_manager.category'),
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
